<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="mailto:qitas@qitas.cn" target="_blank">{{ config.author }}</a><br>
      <a href="http://beian.miit.gov.cn/" target="_blank">  粤ICP备18011880号 </a>
    </div>
    <div id="footer-links">
      <a href="https://twitter.com/QitasTang" class="footer-link" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="https://weibo.com/{{ config.weibo }}" class="footer-link" target="_blank"><i class="fa fa-weibo"></i></a>
      <a href="https://linkedin.com/in/{{ config.linkedin }}" class="footer-link" target="_blank"><i class="fa fa-linkedin"></i></a>
      <a href="https://github.com/{{ config.linkedin }}" class="footer-link" target="_blank"><i class="fa fa-github"></i></a>
    </div>
  </div>
</footer>
