<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="https://github.com/hexojs/hexo/graphs/contributors" target="_blank">{{ config.author }}</a><br>
     Try to smooth the uneven road<a href="https://www.qitas.cn" target="_blank"> under my feet</a>.
    </div>
    <div id="footer-links">
      <a href="https://weibo.com/{{ config.weibo }}" class="footer-link" target="_blank"><i class="fa fa-weibo"></i></a>
      <a href="https://linkedin.com/in/{{ config.linkedin }}" class="footer-link" target="_blank"><i class="fa fa-linkedin"></i></a>
      <a href="https://github.com/{{ config.linkedin }}" class="footer-link" target="_blank"><i class="fa fa-github"></i></a>
    </div>
  </div>
</footer>
